name: Go

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      package: github.com/bububa/oceanengine
    steps:
    - uses: actions/checkout@v3
      with:
        path: src/${{ env.package }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: ${{ env.package }}/go.mod

    - name: Dependencies
      run: go get -t -d -v ${{ env.package }}/...

    - name: Build
      run: go build -v ${{ env.package }}/...

    - name: Test
      env:
        APPKEY: ${{ secrets.APPKEY }}
        SECRET: ${{ secrets.APP_SECRET }}
      run: go test -v ${{ env.package }}/...
