name: goreleaser

on:
  push:
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
      package: src/github.com/${{ github.repository }}
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/${{ env.package }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.GOPATH }}/${{ env.package }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.21.0"
          cache-dependency-path: |
            ${{ env.GOPATH }}/${{ env.package }}/go.mod
            ${{ env.GOPATH }}/${{ env.package }}/go.sum
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
